//Display Frames

GLOBAL_MAIN_FRAME = '#Main_Page_Frame';
GLOBAL_POPUP_FRAME = '#Pop_Up_Frame';
GLOBAL_POPUP_FRAME_ID = 'Pop_Up_Frame';


// Data Frames
GLOBAL_MAIN_DATA_FRAME = '#MAIN_APP_DATA_FRAME';
GLOBAL_MAIN_DATA_FRAME_2 = 'MAIN_APP_DATA_FRAME';

// Main Menu  Modes
HOME_MAIN_MENU_MODE = 1;
SETTINGS_MAIN_MENU_MODE = 2;
DRIVER_MAIN_MENU_MODE = 3;
MAP_MAIN_MENU_MODE = 4;
